age=input("how old are you?:")
print(age)
parents_age=input("how old are your parents?:")
print(parents_age)
parents_name=input("whats you parents name?:")
print(parents_name)
friends_names=input("whats your friends name?:")
print(friends_names)
davitis_macivari=input("is davit grdzelishvilis frige working?:")
print(davitis_macivari)